### ISSUE TITLE
Highlight query matched chars

### ISSUE THREAD

**Issue by jacek-kurlit** [jacek-kurlit/pik#12]
Probably will work well after this https://github.com/jacek-kurlit/pik/issues/2

Since we will have matched indexes we can think about handling too long values in process table

**Comment by grouzen** [comment]
This one will be possible only if we use [fuzzy search](https://github.com/jacek-kurlit/pik/issues/2) for all types of queries.

**Comment by jacek-kurlit** [comment]
> This one will be possible only if we use [fuzzy search](https://github.com/jacek-kurlit/pik/issues/2) for all types of queries.

Yes that was my plan - replace contains query with fuzzy to provide hightlight and better UX

**Comment by grouzen** [comment]
It seems this conversation is scattered across the issues :) 

This is my [comment](https://github.com/jacek-kurlit/pik/issues/2#issuecomment-2378972504) from another thread:
> What do you think about applying this to the rest of the types of queries? I guess it will only be Cmd and probably Args. I don't think it is good to add it for ports search.

**Comment by jacek-kurlit** [comment]
Implementation ready it just waits for general refactor because there is a lot to do before it can be merged
