### ISSUE TITLE
telescope like fuzzy search

### ISSUE THREAD

**Issue by jacek-kurlit** [jacek-kurlit/pik#2]
Currently search matches exact words but in case of searching through path it is better to use fuzzy search like in nvim telescope.

**Comment by jacek-kurlit** [comment]
This lookspromising https://github.com/lotabout/fuzzy-matcher

**Comment by grouzen** [comment]
I am interested in implementing this one and have been looking into it for a while.

**Comment by grouzen** [comment]
What do you think about applying this to the rest of the types of queries? I guess it will only be `Cmd` and probably `Args`. I don't think it is good to add it for ports search.

**Comment by jacek-kurlit** [comment]
Yes I would apply this to all other queries including ports since now pik is using contains to search for ports this is why you can start typing port ':8' and it will return all ports containing 8

**Comment by jacek-kurlit** [comment]
Now I see that my first comment under this thread is misleading, I didn't mean only Path to have fuzzy search but all of queries. I just haven't update this.
Sorry for misleading

**Comment by grouzen** [comment]
I'll do it for the rest of them then.

**Comment by grouzen** [comment]
@jacek-kurlit  I think this one can be closed.
