### ISSUE TITLE
[Question] Any advantages to pik on using fzf+ps?

### ISSUE THREAD

**Issue by YasserKa** [jacek-kurlit/pik#68]
I was wondering if pik provides any advantages on using `fzf` with `ps` and ([garabik/grc: generic colouriser](https://github.com/garabik/grc) for colorizing).

```bash
# Search processes
fps() {
	grc --colour=on ps --user "$USER" -o ppid,pid,stime,etime,args | sed 1d \
		| fzf --multi --ansi --preview-window=down,3,wrap,border-none,hidden \
		--preview 'grc --colour=on ps -F {2} | sed 1d' \
		--bind 'alt-t:change-preview-window(down|hidden)' | awk '{print $2}'
	}

# Kill processes
fkill() {
	local -r pid="$(fps)"

	if [[ "$pid" ]]; then
		echo "$pid" | xargs kill "-${1:-9}"
	fi
}
```

Example of output 
![image](https://github.com/user-attachments/assets/fd8eb660-4b30-4633-a187-7f10c8ae3914)

**Comment by jacek-kurlit** [comment]
Hi,

As far as I know fzf will search in every column, pik allows to choose specific or use search everywhere feature.
I had plans to add more features like multi-criteria search, displaying family of process, process kill actions (like choosing kill signal) etc.

May I know how you have discovered pik? I'm wondering why there is sudden interest raising in it.
Thanks in advance!

**Comment by YasserKa** [comment]
> As far as I know fzf will search in every column, pik allows to choose specific or use search
> everywhere feature. 

It's possible to limit fzf's search on specific columns with `--nth`. I don't know if it's possible
to do it while interactively choosing candidates.

> May I know how you have discovered pik? I'm wondering why there is sudden interest raising in it. Thanks in advance!

I follow an RSS feed for CLI/TUI tools: [Terminal Trove - The $HOME of all things in the terminal.](https://terminaltrove.com/)

I found it on today's feed: [pik - A TUI for interactively stopping processes.](https://terminaltrove.com/pik/)

**Comment by jacek-kurlit** [comment]
Ok wow, I was wondering why number of stars increased out of sudden.
Thanks!
