### ISSUE TITLE
Allow faster scrolling using PgUp/PgDown

### ISSUE THREAD

**Issue by grouzen** [jacek-kurlit/pik#72]
Scrolling through the processes list with PgUp/PgDown buttons would be helpful.

**Comment by grouzen** [comment]
Thanks for the app btw! I hate using `ps aux` moronic unix shit from the 70s.

**Comment by jacek-kurlit** [comment]
Hi,
Sure thing we may use PgUp/Down
Do you mind creating Pr for that?

**Comment by grouzen** [comment]
Sure, I would be happy to add it. Cheers!
