### ISSUE TITLE
feat: add support for adding tcp and http processes as well

### ISSUE THREAD

**Issue by devHaitham481** [jacek-kurlit/pik#73]
I find this would be a really neat add where users could easily list all tcp or http processes and be able to interact with them instead of currently running `sudo lsof -t -i:<port-number>`

**Comment by jacek-kurlit** [comment]
Hi!
Interesting feature. I'm java dev so usually I'm only interested in ports take by some server.
Can you describe your use case more?
To be honest I have never used lsof to check for taken ports and pik supports find processes by used ports.

**Comment by devHaitham481** [comment]
actually, `pik` seems to be already supporting my needed feature. in `nodejs` when you're running an application or a server, it needs a port to run on like say `3000` and when you run another instance of an application on the same port, you'd get `port 3000 is already running` in which case you'd have to run `sudo lsof -t -i:3000` to find out the process id and then run `sudo kill <process-id>` to kill that process. 

luckily, with `pik` now I can just do `:3000` and filter the processes by port and kill on sight :) wonderful work!

**Comment by jacek-kurlit** [comment]
I'm glad that it helped you ;)
Closing
