### ISSUE TITLE
Fix failling test

### ISSUE THREAD

**Issue by jacek-kurlit** [jacek-kurlit/pik#84]
Now I understand why tests are falling on mac (on mine linux distro too!)

We have added fuzzy search that can matches by each char in string but asserts are for contains
In other words on my machine I can search process with name "test" but what I got is not process that contains "test" as substring but a sum of those chars -> "at-spi2-registr" is matched because "aT-spi2-rEgiSTr" is present in name.

**Comment by jacek-kurlit** [comment]
@grouzen I have fund the issue ;)

**Comment by grouzen** [comment]
God damn, nice catch, indeed!
